/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileInput: typeof import('./src/components/FileInput.vue')['default']
    Graphcard: typeof import('./src/components/Graphcard.vue')['default']
    IntermediateQuestionPage: typeof import('./src/components/IntermediateQuestionPage.vue')['default']
    QuestionCard: typeof import('./src/components/QuestionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollView: typeof import('./src/components/ScrollView.vue')['default']
  }
}
